apiVersion: v1
kind: Service
metadata:
  name: blobserver
  namespace: my-namespace
  labels:
    name: blobserver
spec:
  type: NodePort
  ports:
  - name: backend
    port: 5009
    targetPort: 5009
    nodePort: 30009  # Ensure it's within the valid range
  selector:
    app.kubernetes.io/name: blobserver